### PR TITLE
[APP-2988] Input Explanation Text

### PR DESCRIPTION
**Pull request by JamesIves**
Adds the `explanation` prop on top of the input field. I've had to make some changes to how the percent field works, but all of them I feel are probably for the best.

hhzuzuzuz

* Pull down the branch and go into Storybook.
* Find an input field and focus it.
* You'll see the explanation prop in action.
* Also added it to the simple form example within QuestionCard.

- [JIRA Ticket](https://unitedincome.atlassian.net/browse/app-*)

### CODE REVIEW

**Comment by RohitRajendran** [comment]
What Nick said

**Comment by labichn** [comment]
I'm just so disappointed.

**Comment by RohitRajendran** [comment]
We expect so much better from you

**Comment by matthewheck** [comment]
this is shite

**Comment by JamesIves** [comment]
u lot are so mean

**Comment by blakeduncan14** [comment]
Agree with the code coverage comments but otherwise lgtm

**Pull request merged**
